from model.model import Model

self_model = Model()
t1, t2 = self_model.creaGrafo(2007, 2014)
print(t1)
print(t2)
t1, t2 = self_model.dettagliPeso()
print(t1)
print(t2)
t1, t2 = self_model.dettagliComp1()
print(t1)
print(t2)
t1, t2 = self_model.dettagliComp2()
print(t1)
print(t2)
t1 = self_model.cammino(3)
print(t1)