from model.model import Model

self_model = Model()
t1, t2 = self_model.creaGrafo(2007, 2008)
print(t1)
print(t2)
t1, t2 = self_model.dettagliPeso()
print(t1)
print(t2)
t1, t2 = self_model.dettagliComp1()
print(t1)
print(t2)
t1, t2 = self_model.dettagliComp2()
print(t1)
print(t2)
t1 = self_model.cammino(4)
print(t1)